### PR TITLE
Added instruction for openSUSE

### PR DESCRIPTION
**Pull request by DeadMozay**

### CODE REVIEW

**Comment by KirMozor** [comment]
To install on OpenSuse:
1. Install dependencies: `sudo zypper install git dkms kernel-headers kernel-default-devel`
2. Run the installation script `sh install-driver.sh`

**Comment by KirMozor** [comment]
You can also add that this driver supports TP-Link Archer T2U Nano (it's my wifi adapter)

**Comment by morrownr** [comment]
Thanks. I need to look at that last part as it is big. Is there a way to do that last part by just putting a link to a site that explains it?

**Comment by DeadMozay** [comment]
> Thanks. I need to look at that last part as it is big. Is there a way to do that last part by just putting a link to a site that explains it?

Unfortunately, such a link leads to an empty package, users unknowingly put an empty package instead of the kernel module itself, which is why I wrote in detail

**Pull request merged**
