### PR TITLE
changes for kernel v6.9

### PR DESCRIPTION
**Pull request by 5kft**
Hi @morrownr , a simple change is needed for this driver to work in kernel v6.9.  Hope this is helpful!

### CODE REVIEW

**Comment by morrownr** [comment]
Thanks.

**Comment by morrownr** [comment]
@5kft 

Do you have an adapter based on the rtl8821au chip? That is, the version with blurtooth support?

One of the guys working on the in-kernel code is asking. None of working on the driver have adapters with blurtooth.

**Comment by 5kft** [comment]
Hi @morrownr , unfortunately not - my 8821aus are all Wi-Fi only...

**Comment by morrownr** [comment]
@5kft 

The new driver is available for testing and reporting. See issue 133.

See you in issue 133 when you have time.

@morrownr

**Comment by 5kft** [comment]
Unfortunately I'm encountering build issues with the new rtw88 driver, when targeting my embedded ARM-based boards.  I added a comment to https://github.com/morrownr/8821au-20210708/issues/133#issuecomment-2103774443 regarding this.

**Comment by morrownr** [comment]
I'm watching. Mr. Finger will need to work you on that as it is his repo. I don't have the background regarding how he has set everything up and his setup is likely never tested in the way you are using it. I'm just testing and working on parts of the code.

**Comment by 5kft** [comment]
Yeah, I'm not losing sleep over this, as your driver works perfectly for me.  It'll be easier to give his stuff a try when he syncs his latest changes over to linux-next (it is trivial for me to build from that, rather than piecing together the changes directly from his github).

**Comment by morrownr** [comment]
Copy all. I will let you know when he sends the patches to be included in wireless-next.

**Comment by morrownr** [comment]
@5kft 

Well rats. My system for testing new kernels is to use the Ubuntu mainline kernels as that makes it quick and easy and I have plenty of other things to do. So, the Ubuntu mainline kernel system is broken so I have not yet tested kernel 6.12. I could compile it from Linux mainline but I have other things I need to be working on. Have you tested this driver with 6.12?

**Comment by 5kft** [comment]
> Have you tested this driver with 6.12?

Actually I've since switched the the rtw88 driver; it works fine with 6.12-rcX.  I have not tried this one, however...

**Pull request merged**
