### PR TITLE
update build CI

### PR DESCRIPTION
**Pull request by gemesa**
Removed `gcc-9` from the build CI so it is synchronized with the README:

```
...

Tested Compilers

- gcc 10, 11 and 12
...
```

Also moved every step (`gcc-10`, `gcc-11`, `gcc-12`) to the ubuntu 22.04 job in the CI and removed the ubuntu 20.04 job so the CI config is more compact now.

### CODE REVIEW

**Comment by morrownr** [comment]
Good morning @gemesa 

I was in the process of adding gcc 9 back to the README when I saw it in the code you were adding. He he. It is a constant battle for me to keep the amount of work I do to within the amount of time I have available.

The real question is, should we still be testing gcc 9? I dropped it due to time available but if it can be automated, maybe it should be tested if there is still a need. What do you think?

**Comment by gemesa** [comment]
Lets add it back then to the CI and README also, it is very easy because it is preinstalled on the [Ubuntu 22.04 runner image](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md). I cant tell though if we still need it as I always use the latest SWs on my Fedora 37.

**Comment by gemesa** [comment]
Hm, it looks like it can not be built on Ubuntu 22.04 with `gcc-9`:
```
 make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-1034-azure/build M=/home/runner/work/8821au-20210708/8821au-20210708  modules
  make[1]: Entering directory '/usr/src/linux-headers-5.15.0-1034-azure'
  warning: the compiler differs from the one used to build the kernel
    The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    You are using:           gcc-9 (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
    CC [M]  /home/runner/work/8821au-20210708/8821au-20210708/core/rtw_cmd.o
    CC [M]  /home/runner/work/8821au-20210708/8821au-20210708/core/rtw_security.o
  gcc-9: error: unrecognized command line option ‘-mharden-sls=all’
  make[2]: *** [scripts/Makefile.build:297: /home/runner/work/8821au-20210708/8821au-20210708/core/rtw_cmd.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  gcc-9: error: unrecognized command line option ‘-mharden-sls=all’
  make[2]: *** [scripts/Makefile.build:297: /home/runner/work/8821au-20210708/8821au-20210708/core/rtw_security.o] Error 1
  make[1]: *** [Makefile:1906: /home/runner/work/8821au-20210708/8821au-20210708] Error 2
  make: *** [Makefile:2501: modules] Error 2
  make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-1034-azure'
  Error: Process completed with exit code 2.
```

**Comment by gemesa** [comment]
So in the end this PR adds `gcc-10` and `gcc-11` to the ubuntu 22.04 job, and adds `gcc-9` to the README. Let me know if you dont agree with something.

**Pull request merged**
